/t1/my_label2:
  ros__parameters:
    background_b: 255
    background_g: 1
    background_r: 23
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false
